---
abstract: 'Include a customized Twitter Bootstrap in your distribution'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Config::INI::Reader: 0
  File::HomeDir::Test: 0
  IO::Capture::Stdout: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-TwitterBootstrap
requires:
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::Plugin: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Path::Class: 0
  Template: 0
  Template::Provider::FromDATA: 0
  Text::Glob: 0
  WebService::TwitterBootstrap::Download::Custom: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/plicease/Dist-Zilla-Plugin-TwitterBootstrap/issues
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-TwitterBootstrap/
  repository: git://github.com/plicease/Dist-Zilla-Plugin-TwitterBootstrap.git
version: 0.04
